version: "3"
services:
 server:
     build:
       context: .
    #image: docker.io/donjuanplatinum/xnote:latest   
     container_name: xnote
     volumes:
       - ./data:/home/data
       - ./boot.properties:/home/config/boot/boot.sae.properties
       - ../xnote:/home
     ports:
       - 1234:1234
