version: "3"
services:
 server:
     build:
       context: .
    #image: docker.io/donjuanplatinum/xnote:latest   
     container_name: xnote
     volumes:
       - ./data:/xnote/data
       - ./boot.properties:/config/boot/boot.docker.properties
       - ../xnote:/xnote
     ports:
       - 1234:1234
